# -*- coding: utf-8 -*-
"""LLMSocialNavWorkbook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rbmmNKaXXwTJr5VmK3rJNP5yKRK8KPtK
"""

!pip install -q gemma

import pandas as pd
import numpy as np
from difflib import SequenceMatcher
from gemma import gm

# SETTINGS
use_symbolic_baseline = False  # Set to False to use baby names, True for symbols
shuffle_adj_list = True
one_tok = True
shuffle_adj_prompts = False
shuffle_opts = True

# Only load real names if we AREN'T using the symbolic baseline
if not use_symbolic_baseline:
    filtered_names = filter_names(unique_names, use_filter_tok=one_tok)
else:
    # If using symbolic baseline, make sure we don't overwrite the symbols
    # This ensures filtered_names stays as the symbols you generated earlier
    print(f"Keeping symbolic baseline names. Count: {len(filtered_names)}")

print(filtered_names[:20])

"""# Helper functions"""

def filter_names_with_tokenizer(names, tokenizer=None, use_filter_tok=True, use_filter_sim=True):

    def filter_tok(names_list):
        # If tokenizer was never defined, use the length-based backup
        if tokenizer is None:
            print("Warning: No tokenizer found. Falling back to 4-letter limit.")
            return [n.strip() for n in names_list if 1 < len(n.strip()) <= 4]

        one_token_names = []
        for n in names_list:
            name_strip = n.strip()
            # The 'tokenizer' variable must exist for this line to work:
            tokens = tokenizer.encode(name_strip, add_special_tokens=False)
            if len(tokens) == 1:
                one_token_names.append(name_strip)
        return one_token_names

    def filter_sim(names_list):
        from difflib import SequenceMatcher
        def similar(a, b):
            return SequenceMatcher(None, a, b).ratio()

        filtered_list = []
        for n in names_list:
            exists = False
            for m in filtered_list:
                if similar(n, m) > 0.70:
                    exists = True
                    break
            if not exists:
                filtered_list.append(n)
        return filtered_list

    result = names
    if use_filter_tok:
        result = filter_tok(result)
    if use_filter_sim:
        result = filter_sim(result)

    return result

# TWEAK: Added use_symbolic_baseline=False to the arguments
def generate_adj_list(names, shuffle_adj_list=True, one_tok=False, use_symbolic_baseline=False):
  adj_list_suffix = 'adj-list-shuffled' if shuffle_adj_list else 'adj-list-ordered'

  # TWEAK: Logic to handle the new random-symbols suffix
  if use_symbolic_baseline:
    tok_suffix = 'random-symbols'
  else:
    tok_suffix = 'one-token-names' if one_tok else 'all-names'

  suffix = f'{adj_list_suffix}_{tok_suffix}'
  np.random.seed(42)

  all_adj_sentences = []
  all_id_to_names = []

  for _ in range(100):
    np.random.shuffle(names)
    selected_names = names[:13]

    # --- Graph Structure Definition ---
    # Mapping 1-13 (user input) to 0-12 (array indices)
    # Node 1 -> Index 0
    # Node 2 -> Index 1
    # ...
    # Node 13 -> Index 12

    adj = {
      0: [1, 7],           # 1 connects to 2, 8 (Indices: 1, 7)
      1: [0, 3, 2],        # 2 connects to 1, 4, 3 (Indices: 0, 3, 2)
      2: [1, 3, 4],        # 3 connects to 2, 4, 5 (Indices: 1, 3, 4)
      3: [1, 2, 4, 5],     # 4 connects to 2, 3, 5, 6 (Indices: 1, 2, 4, 5)
      4: [2, 3, 6],        # 5 connects to 3, 4, 7 (Indices: 2, 3, 6)
      5: [3, 6],           # 6 connects to 4, 7 (Indices: 3, 6)
      6: [4, 5],           # 7 connects to 5, 6 (Indices: 4, 5)
      7: [0, 8, 9],        # 8 connects to 1, 9, 10 (Indices: 0, 8, 9)
      8: [7, 10],          # 9 connects to 8, 11 (Indices: 7, 10)
      9: [7, 11],          # 10 connects to 8, 12 (Indices: 7, 11)
      10: [8, 11, 12],     # 11 connects to 9, 12, 13 (Indices: 8, 11, 12)
      11: [9, 10, 12],     # 12 connects to 10, 11, 13 (Indices: 9, 10, 12)
      12: [10, 11]         # 13 connects to 11, 12 (Indices: 10, 11)
    }

    # --- Generate Prompt String ---

    sentences = []
    # Iterate through nodes in order (0 to 12)
    for i in range(13):
      name_i = selected_names[i]
      # Get list of friends (neighbors) for this person
      neighbors = sorted(adj[i])

      for n_idx in neighbors:
        name_n = selected_names[n_idx]
        sentence = f"{name_i} is friends with {name_n}."
        sentences.append(sentence)

    if shuffle_adj_list:
      np.random.shuffle(sentences)

    all_adj_sentences.append(sentences)
    all_id_to_names.append(selected_names)

  adj_list = pd.DataFrame([all_adj_sentences, all_id_to_names]).T
  adj_list.to_csv(f'adj-list_{suffix}.csv', index=False)

  return adj_list

# TWEAK: Added use_symbolic_baseline=False to the arguments
def generate_questions(adj_list, tasks, shuffle_adj_list=True, one_tok=False,
                       shuffle_adj_prompts=False, shuffle_opts=True, use_symbolic_baseline=False):
  np.random.seed(42)

  adj_list_suffix = 'adj-list-shuffled' if shuffle_adj_list else 'adj-list-ordered'

  # TWEAK: Logic to handle the new random-symbols suffix
  if use_symbolic_baseline:
    tok_suffix = 'random-symbols'
  else:
    tok_suffix = 'one-token-names' if one_tok else 'all-names'

  adj_prompts_suffix = 'adj-prompt-shuffled' if shuffle_adj_prompts else 'adj-prompt-ordered'
  opts_suffix = 'choices-shuffled' if shuffle_opts else 'choices-ordered'
  suffix = f'{adj_list_suffix}_{tok_suffix}_{adj_prompts_suffix}_{opts_suffix}'

  questions = []
  startpoints = []
  endpoints = []
  opt1s = []
  opt2s = []
  correct_choices = []
  question_ids = []
  prompt_ids = []

  for i in range(len(adj_list)):
    curr_prompt, curr_names = adj_list.iloc[i, 0], adj_list.iloc[i, 1]

    for index, row in tasks.iterrows():
      temp_prompt = curr_prompt.copy()

      if shuffle_adj_prompts:
        np.random.shuffle(temp_prompt)
      temp_prompt = ' '.join(temp_prompt)

      name1 = curr_names[row['startpoint_id'] - 1]
      name2 = curr_names[row['endpoint_id'] - 1]
      name3 = curr_names[row['opt1_id'] - 1]
      name4 = curr_names[row['opt2_id'] - 1]
      correct_choice = curr_names[row['correct_choice'] - 1]

      name_opts = [name3, name4]

      if shuffle_opts:
        np.random.shuffle(name_opts)

      name3, name4 = name_opts

      question = f"{name1} wants to pass a message most efficiently to {name2}, should {name1} begin by passing the message on to {name3} or {name4}?"
      question = " ".join([temp_prompt, question])
      questions.append(question)

      startpoints.append(name1)
      endpoints.append(name2)
      opt1s.append(name3)
      opt2s.append(name4)
      correct_choices.append(correct_choice)

      question_ids.append(index)
      prompt_ids.append(i)

  all_questions = pd.DataFrame([questions, startpoints, endpoints, opt1s, opt2s, correct_choices, question_ids, prompt_ids]).T
  all_questions.columns = ["question", "startpoint", "endpoint", "opt1", "opt2", "correct_choice", "question_id", "prompt_id"]
  all_questions.to_csv(f'questions_{suffix}.csv', index=False)

  return all_questions

import random
import string

def generate_symbolic_names(count, length=5):
    """Generates a list of unique strings made of random symbols, letters, and digits."""
    # TWEAK: Added ascii_letters and digits to the character pool
    chars = "!@#$%^&*()-_=+[]{}|;:,.<>?" + string.ascii_letters + string.digits
    symbolic_names = set()

    while len(symbolic_names) < count:
        new_name = ''.join(random.choices(chars, k=length))
        symbolic_names.add(new_name)

    return list(symbolic_names)

"""# Prompts v1

All unique names below similarity threshold
"""

shuffle_adj_list = True
one_tok = False
shuffle_adj_prompts = False
shuffle_opts = True

# Load the dataset
df = pd.read_csv('./Popular_Baby_Names.csv')

# Preprocessing: unique, lowercase, and strip whitespace
unique_names = df["Child's First Name"].astype(str).str.strip().str.lower().unique()
len(unique_names)

tasks = pd.read_csv('./son_et_al_nhb_2024_nav_problems.csv')
tasks

# Check if we should use symbols or real names
if use_symbolic_baseline:
    # This calls the generator function you already have in Cell 8
    filtered_names = generate_symbolic_names(1000)
    print(f"SYMBOL MODE: Generated {len(filtered_names)} unique symbolic strings.")
else:
    # Original logic for real baby names
    filtered_names = filter_names(unique_names, use_filter_tok=one_tok)
    print(f"REAL NAME MODE: Using {len(filtered_names)} baby names.")

# Show the first 5 to verify they are symbols
print(f"Sample: {filtered_names[:5]}")

sorted(filtered_names)

adj_list = generate_adj_list(filtered_names,
                             shuffle_adj_list=shuffle_adj_list,
                             one_tok=one_tok, # Passes 'True'
                             use_symbolic_baseline=use_symbolic_baseline)

# Pass use_symbolic_baseline here as well
all_questions = generate_questions(adj_list, tasks,
                                   shuffle_adj_list=shuffle_adj_list,
                                   shuffle_opts=shuffle_opts,
                                   shuffle_adj_prompts=shuffle_adj_prompts,
                                   one_tok=one_tok,
                                   use_symbolic_baseline=use_symbolic_baseline)
all_questions

"""Only respond with \'{name3}\' or \'{name4}\'

# Prompts v2

Only one-token names
"""

shuffle_adj_list = True
one_tok = True
shuffle_adj_prompts = False
shuffle_opts = True

# 1. Initialize the Gemma Model and Tokenizer
# This is done once to provide the function with the model's vocabulary
try:
    print("Initializing Gemma Model and Tokenizer...")
    # Loading the model-id you intend to use (e.g., 3-4b-it)
    model = gm.Gemma3("google/gemma-3-4b-it")
    tokenizer = model.tokenizer
    print("Tokenizer loaded successfully.")
except Exception as e:
    print(f"Error loading model: {e}")
    print("Ensure you have granted access to the model and ran the !pip install cell.")

# 2. Determine Mode and Run Filter
if use_symbolic_baseline:
    # Logic for generating random symbolic strings if toggle is True
    import random
    import string

    # This calls your symbolic generator (likely defined in Cell 9)
    filtered_names = generate_symbolic_names(1000)
    print(f"SYMBOL MODE: Generated {len(filtered_names)} unique symbolic strings.")
else:
    # Use the REAL tokenizer to check every name from your loaded dataset
    # We pass the tokenizer directly to the function to avoid scope issues
    filtered_names = filter_names_with_tokenizer(unique_names, tokenizer, use_filter_tok=one_tok)
    print(f"REAL NAME MODE: Found {len(filtered_names)} verified one-token names.")

# 3. Final Verification Output
print(f"Sample of processed names: {filtered_names[:10]}")

sorted(filtered_names)

# Check if we should use symbols or real names
if use_symbolic_baseline:
    # This generates the symbols directly if the toggle is True
    import random
    chars = "!@#$%^&*()-_=+[]{}|;:,.<>?"
    symbolic_set = set()
    while len(symbolic_set) < 1000:
        symbolic_set.add(''.join(random.choices(chars, k=5)))
    filtered_names = list(symbolic_set)
    print(f"SYMBOL MODE: Generated {len(filtered_names)} symbols.")
else:
    # Original logic for real baby names
    filtered_names = filter_names(unique_names, use_filter_tok=one_tok)
    print(f"REAL NAME MODE: Using {len(filtered_names)} baby names.")

# Show a sample to verify
print(f"Sample: {filtered_names[:5]}")

# Pass use_symbolic_baseline here as well
all_questions = generate_questions(adj_list, tasks,
                                   shuffle_adj_list=shuffle_adj_list,
                                   shuffle_opts=shuffle_opts,
                                   shuffle_adj_prompts=shuffle_adj_prompts,
                                   one_tok=one_tok,
                                   use_symbolic_baseline=use_symbolic_baseline)
all_questions

# Sort them alphabetically so it's easier for your eyes to spot patterns
sorted_names = sorted(filtered_names)

# Print them in groups of 10 per line so the list isn't just one giant vertical column
for i in range(0, len(sorted_names), 10):
    print(", ".join(sorted_names[i:i+10]))

print(f"\nTotal names to check: {len(sorted_names)}")